### ISSUE TITLE
Topic Idea: Automating Code Reviews

### ISSUE THREAD

**Issue by redross** [devchattv/rubyroguestopics#17]
Guest Recommendation: [Mindaugas Mozūras](https://github.com/mmozuras/), an author of a gem called [Pronto](https://github.com/mmozuras/pronto), related to this very topic.

He also talks a lot about consistency/[choose-boring-technology](http://mcfunley.com/choose-boring-technology), so touching on things related to ones in [episode #229](https://devchat.tv/ruby-rogues/229-rr-adopting-new-technology) could also be interesting.

**Comment by therubyrep** [comment]
Reached out to Mindaugas Mozūras (1/23/16).
