### ISSUE TITLE
Crystal (http://crystal-lang.org/)

### ISSUE THREAD

**Issue by cmaxw** [devchattv/rubyroguestopics#8]

**Comment by qhwa** [comment]
+1

Especially want to see how to use Crystal together with Ruby.

I'm building a product which provides both web application and command-line tool for users. I use Crystal to make the CLI tool and feels super great at reusing most of the logics from the Ruby Application.

**Comment by therubyrep** [comment]
Reached out on the community forum (https://groups.google.com/forum/?fromgroups#!forum/crystal-lang) on 1/23/16 to see if there's any interest.
